import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/Hero';
import axios from 'axios';
import { useState, useEffect } from 'react';

const apiKey = '563492ad6f91700001000001a6302b3004b54911be85dfca7876986b';

export default function Home({ data }) {
  const [page, setPage] = useState(2);
  const [first, setFirst] = useState([]);
  const [second, setSecond] = useState([]);
  const [third, setThird] = useState([]);
  const [fourth, setFourth] = useState([]);
  const url = `https://api.pexels.com/v1/search?query=tigers&page=${page}&per_page=20`;

  const photos = data.photos.map((photo) => (
    <div className="photo" key={photo.id}>
      <img src={photo.src.large} alt="" />
    </div>
  ));

  useEffect(() => {
    const photos3 = [...photos];
    const portion = Math.ceil(photos3.length / 4);
    setFirst(photos3.slice(0, portion));
    setSecond(photos3.slice(portion, portion * 2));
    setThird(photos3.slice(portion * 2, portion * 3));
    setFourth(photos3.slice(portion * 3));
  }, []);

  // const portion = Math.ceil(photos3.length / 4);
  // const first = photos3.slice(0, portion);
  // const second = photos3.slice(portion, portion * 2);
  // const third = photos3.slice(portion * 2, portion * 3);
  // const fourth = photos3.slice(portion * 3);
  // console.log(first.length, second.length, third.length, fourth.length);

  const photos2 = [...photos].reverse();

  const loadMore = async () => {
    setPage((prevPage) => {
      return prevPage + 1;
    });
    const res = await axios.get(url, {
      headers: {
        Accept: 'application/json',
        Authorization: apiKey,
      },
    });

    const data = await res.data;

    const photoList = data.photos.map((photo) => (
      <div className="photo" key={photo.id}>
        <img src={photo.src.large} alt="" />
      </div>
    ));

    const portion = Math.ceil(photoList.length / 4);
    setFirst((prevFirst) => {
      return [...prevFirst, ...photoList.slice(0, portion)];
    });
    setSecond((prevSecond) => {
      return [...prevSecond, ...photoList.slice(portion, portion * 2)];
    });
    setThird((prevThird) => {
      return [...prevThird, ...photoList.slice(portion * 2, portion * 3)];
    });
    setFourth((prevFourth) => {
      return [...prevFourth, ...photoList.slice(portion * 3)];
    });
    // setFirst(photoList.slice(0, portion));
    // setSecond(photoList.slice(portion, portion * 2));
    // setThird(photoList.slice(portion * 2, portion * 3));
    // setFourth(photoList.slice(portion * 3));
    // setFirst((prev) => {
    //   return [...prev, ...photoList];
    // });
  };

  return (
    <div>
      <Head>
        <title>Free stock photos and videos for free</title>
        <meta name="description" content="Generated by create next app | Pexels photo library | Hassuu pexels free stock photos" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Hero />
        <div className="row">
          <div className="column">{first}</div>
          <div className="column">{second}</div>
          <div className="column">{third}</div>
          <div className="column">{fourth}</div>
        </div>
        {/* <div className="gallery">{photos}</div> */}
      </main>

      <div className="loadmore">
        <button className="button" onClick={loadMore}>
          Load More
        </button>
      </div>

      <footer></footer>
    </div>
  );
}

export async function getStaticProps() {
  const url = `https://api.pexels.com/v1/search?query=tigers&page=1&per_page=20`;
  const res = await axios.get(url, {
    headers: {
      Accept: 'application/json',
      Authorization: apiKey,
    },
  });

  // console.log(res.data);
  // const json = await res.json();

  return {
    props: { data: res.data },
  };
}
