import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Free stock photos and videos for free</title>
        <meta name="description" content="Generated by create next app | Pexels photo library | Hassuu pexels free stock photos" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      </main>

      <footer></footer>
    </div>
  );
}
